// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService handles user authentication (login/logout/session/setup).
 * Bound to Wails — methods are callable from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * ChangePassword changes the admin password. Only users with role 'admin' can change password.
 */
export function ChangePassword(oldPassword: string, newPassword: string): $CancellablePromise<void> {
    return $Call.ByID(622983113, oldPassword, newPassword);
}

/**
 * GetCurrentUser returns the currently logged in user session.
 */
export function GetCurrentUser(): $CancellablePromise<models$0.UserSession | null> {
    return $Call.ByID(2275703454);
}

/**
 * IsLoggedIn returns whether a user is currently logged in.
 */
export function IsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(192641601);
}

/**
 * IsSetupRequired checks if an admin account exists in the database.
 * If no admin user is found, setup is required.
 */
export function IsSetupRequired(): $CancellablePromise<boolean> {
    return $Call.ByID(3886404712);
}

/**
 * Login validates credentials and establishes an in-memory session.
 */
export function Login(username: string, password: string): $CancellablePromise<models$0.UserSession | null> {
    return $Call.ByID(1046395749, username, password);
}

/**
 * Logout clears the current in-memory user session.
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(728727406);
}

/**
 * SetupAdmin registers the first admin account when the app is launched for the first time.
 */
export function SetupAdmin(username: string, password: string, displayName: string): $CancellablePromise<models$0.UserSession | null> {
    return $Call.ByID(753686116, username, password, displayName);
}
