// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DashboardService provides aggregated data for the dashboard view.
 * Bound to Wails — methods are callable from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetDashboardData returns all data needed for the dashboard:
 * today's stats, monthly revenue, and top 5 products.
 */
export function GetDashboardData(): $CancellablePromise<models$0.DashboardData> {
    return $Call.ByID(3980096684);
}

/**
 * GetMonthlySalesData returns daily sales data for a given year/month (for charts).
 */
export function GetMonthlySalesData(year: number, month: number): $CancellablePromise<models$0.DailySales[] | null> {
    return $Call.ByID(595144631, year, month);
}
