// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EmployeeService provides staff account management (admin CRUD).
 * Bound to Wails — methods are callable from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateStaff creates a new employee account.
 */
export function CreateStaff(req: models$0.CreateStaffRequest): $CancellablePromise<models$0.User | null> {
    return $Call.ByID(3982458784, req);
}

/**
 * DeleteStaff removes an employee account. Admin accounts cannot be deleted here.
 */
export function DeleteStaff(id: number): $CancellablePromise<void> {
    return $Call.ByID(1519488357, id);
}

/**
 * GetAllUsersForFilter returns all active accounts (admin & employees) for filtering in history view.
 */
export function GetAllUsersForFilter(): $CancellablePromise<models$0.UserSession[] | null> {
    return $Call.ByID(3110228220);
}

/**
 * GetStaffList returns all employee accounts.
 */
export function GetStaffList(): $CancellablePromise<models$0.User[] | null> {
    return $Call.ByID(1648378616);
}

/**
 * ResetStaffPassword allows admin to set a new password for an employee.
 */
export function ResetStaffPassword(id: number, newPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2952121920, id, newPassword);
}

/**
 * UpdateStaff updates an employee's display name.
 */
export function UpdateStaff(req: models$0.UpdateStaffRequest): $CancellablePromise<void> {
    return $Call.ByID(1062089107, req);
}
