// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProductService handles CRUD operations for products.
 * Bound to Wails — methods are callable from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateProduct inserts a new product into the database.
 */
export function CreateProduct(p: models$0.Product): $CancellablePromise<models$0.Product> {
    return $Call.ByID(2090427622, p);
}

/**
 * DeleteProduct performs a soft-delete by setting is_active = false.
 */
export function DeleteProduct(id: number): $CancellablePromise<void> {
    return $Call.ByID(4076982595, id);
}

/**
 * GetCategories returns a list of unique product categories.
 */
export function GetCategories(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4152447289);
}

/**
 * GetProductByID returns a single product by its ID.
 */
export function GetProductByID(id: number): $CancellablePromise<models$0.Product> {
    return $Call.ByID(4158759504, id);
}

/**
 * GetProducts returns a filtered list of products.
 * search: filters by product name (partial match).
 * category: filters by exact category (empty = all).
 * status: "active", "inactive", or "" (all).
 */
export function GetProducts(search: string, category: string, status: string): $CancellablePromise<models$0.Product[] | null> {
    return $Call.ByID(3748633137, search, category, status);
}

/**
 * UpdateProduct updates an existing product.
 */
export function UpdateProduct(p: models$0.Product): $CancellablePromise<void> {
    return $Call.ByID(3757926869, p);
}
