// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReportService generates daily PDF reports.
 * Bound to Wails — methods are callable from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GenerateDailyReport generates a daily PDF report and returns it as bytes.
 * date should be in "YYYY-MM-DD" format.
 */
export function GenerateDailyReport(date: string): $CancellablePromise<string | null> {
    return $Call.ByID(784953506, date);
}

/**
 * GetDailyReportData gathers all data needed for the daily report.
 * Bound to Wails — callable from frontend to display on-screen report.
 */
export function GetDailyReportData(date: string): $CancellablePromise<models$0.DailyReportData> {
    return $Call.ByID(32074575, date);
}

/**
 * SaveDailyReport generates the daily report PDF and saves it to the given file path.
 * The frontend should use Wails' native save dialog to get filePath from the user.
 */
export function SaveDailyReport(date: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(149528176, date, filePath);
}
