// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StockWithdrawalService handles stock withdrawals when owner/staff takes items from store.
 * Bound to Wails — methods are callable from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateWithdrawal records a new stock withdrawal and decreases product inventory.
 */
export function CreateWithdrawal(req: models$0.CreateWithdrawalRequest): $CancellablePromise<models$0.StockWithdrawal | null> {
    return $Call.ByID(2340916414, req);
}

/**
 * GetWithdrawals returns history of stock withdrawals with optional date filtering.
 */
export function GetWithdrawals(startDate: string, endDate: string): $CancellablePromise<models$0.StockWithdrawal[] | null> {
    return $Call.ByID(4092998701, startDate, endDate);
}
