// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransactionService handles creating, listing, and voiding transactions.
 * Bound to Wails — methods are callable from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateTransaction creates a new transaction with items.
 * Uses the currently logged-in user as the employee handling the transaction.
 */
export function CreateTransaction(req: models$0.CreateTransactionRequest): $CancellablePromise<models$0.Transaction> {
    return $Call.ByID(652992384, req);
}

/**
 * ExportTransactionsCSV exports transactions (one row per item line) as
 * CSV text for backup. Filters match GetTransactions; empty means all.
 * The file is ';' separated with a UTF-8 BOM so Microsoft Excel (id-ID
 * locale) opens it correctly. Numbers are written raw so Excel can sum them.
 */
export function ExportTransactionsCSV(startDate: string, endDate: string, employeeFilter: string): $CancellablePromise<string> {
    return $Call.ByID(596933177, startDate, endDate, employeeFilter);
}

/**
 * GetTransactionByID returns a single transaction with its items.
 */
export function GetTransactionByID(id: number): $CancellablePromise<models$0.Transaction> {
    return $Call.ByID(1791151672, id);
}

/**
 * GetTransactions returns a list of transactions with optional filters.
 * startDate and endDate should be in "YYYY-MM-DD" format.
 * employeeFilter: username or display name, or "" for all.
 */
export function GetTransactions(startDate: string, endDate: string, employeeFilter: string): $CancellablePromise<models$0.Transaction[] | null> {
    return $Call.ByID(2760386793, startDate, endDate, employeeFilter);
}

/**
 * ImportTransactionsCSV restores transactions from a CSV backup file created
 * by ExportTransactionsCSV. The frontend reads the file as text and passes
 * its content here.
 * 
 * Safety rules (by design):
 *   - Existing transaction codes are SKIPPED (import is idempotent —
 *     re-importing the same file never duplicates data).
 *   - Stock is NOT touched: import restores historical records only,
 *     current stock stays as-is.
 *   - Only admins may import (checked when a session exists).
 *   - Cashier names are matched to users by display name/username;
 *     unknown names fall back to the importing admin.
 */
export function ImportTransactionsCSV(csvText: string): $CancellablePromise<models$0.ImportTransactionsResult> {
    return $Call.ByID(4110655324, csvText);
}

/**
 * VoidTransaction marks a transaction as void and restores product stock.
 */
export function VoidTransaction(id: number, reason: string): $CancellablePromise<void> {
    return $Call.ByID(890015626, id, reason);
}
