// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransactionService handles creating, listing, and voiding transactions.
 * Bound to Wails — methods are callable from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateTransaction creates a new transaction with items.
 * Uses the currently logged-in user as the employee handling the transaction.
 */
export function CreateTransaction(req: models$0.CreateTransactionRequest): $CancellablePromise<models$0.Transaction> {
    return $Call.ByID(652992384, req);
}

/**
 * GetTransactionByID returns a single transaction with its items.
 */
export function GetTransactionByID(id: number): $CancellablePromise<models$0.Transaction> {
    return $Call.ByID(1791151672, id);
}

/**
 * GetTransactions returns a list of transactions with optional filters.
 * startDate and endDate should be in "YYYY-MM-DD" format.
 * employeeFilter: username or display name, or "" for all.
 */
export function GetTransactions(startDate: string, endDate: string, employeeFilter: string): $CancellablePromise<models$0.Transaction[] | null> {
    return $Call.ByID(2760386793, startDate, endDate, employeeFilter);
}

/**
 * VoidTransaction marks a transaction as void and restores product stock.
 */
export function VoidTransaction(id: number, reason: string): $CancellablePromise<void> {
    return $Call.ByID(890015626, id, reason);
}
