// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CartItem is used when creating a new transaction
 */
export interface CartItem {
    "product_id": number;
    "qty": number;
}

/**
 * CreateStaffRequest is the input for creating a new employee account
 */
export interface CreateStaffRequest {
    "username": string;
    "password": string;
    "display_name": string;
}

/**
 * CreateTransactionRequest is the input for creating a new transaction.
 * EmployeeID is no longer provided by the caller — it is taken from the logged-in session.
 */
export interface CreateTransactionRequest {
    "payment_method": string;
    "note": string;
    "items": CartItem[] | null;
}

/**
 * CreateWithdrawalRequest is the input for creating a stock withdrawal
 */
export interface CreateWithdrawalRequest {
    "product_id": number;
    "qty": number;
    "reason": string;
}

/**
 * DailyReportData holds all data needed to generate the daily PDF report
 */
export interface DailyReportData {
    "report_date": string;
    "printed_at": string;
    "total_revenue": number;
    "total_transactions": number;
    "total_items_sold": number;
    "stock_report": StockReportItem[] | null;
    "by_employee": EmployeeTransactions[] | null;
}

/**
 * DailySales represents sales data for a single day (used in charts)
 */
export interface DailySales {
    "date": string;
    "revenue": number;
    "count": number;
}

/**
 * DashboardData holds all data for the dashboard view
 */
export interface DashboardData {
    "today_revenue": number;
    "today_transactions": number;
    "today_items_sold": number;
    "monthly_revenue": number;
    "monthly_data": DailySales[] | null;
    "top_products": TopProduct[] | null;
}

/**
 * EmployeeTransactions groups transactions by employee for the report
 */
export interface EmployeeTransactions {
    "employee_name": string;
    "transactions": Transaction[] | null;
    "subtotal_amount": number;
    "transaction_count": number;
    "items_sold": number;
}

/**
 * Product represents a product in the store inventory
 */
export interface Product {
    "id": number;
    "name": string;
    "category": string;
    "sell_price": number;
    "cost_price": number;
    "stock": number;
    "unit": string;
    "is_active": boolean;
    "created_at": string;
    "updated_at": string;
}

/**
 * StockReportItem represents a product's stock status in the daily report
 */
export interface StockReportItem {
    "product_name": string;
    "unit": string;
    "sold_today": number;
    "current_stock": number;
}

/**
 * StockWithdrawal represents a stock withdrawal record (owner takes product from store)
 */
export interface StockWithdrawal {
    "id": number;
    "product_id": number;
    "product_name": string;
    "qty": number;
    "reason": string;
    "withdrawn_by": number;
    "withdrawn_by_name": string;
    "created_at": string;
}

/**
 * TopProduct represents a top-selling product
 */
export interface TopProduct {
    "product_id": number;
    "product_name": string;
    "total_qty": number;
    "total_amount": number;
}

/**
 * Transaction represents a sales transaction
 */
export interface Transaction {
    "id": number;
    "transaction_code": string;
    "employee_id": number;
    "employee_name": string;
    "total_amount": number;
    "payment_method": string;
    "note": string;
    "is_void": boolean;
    "void_reason": string;
    "created_at": string;
    "items"?: TransactionItem[] | null;
}

/**
 * TransactionItem represents a line item within a transaction
 */
export interface TransactionItem {
    "id": number;
    "transaction_id": number;
    "product_id": number;
    "product_name": string;
    "qty": number;
    "unit_price": number;
    "subtotal": number;
}

/**
 * UpdateStaffRequest is the input for updating an employee account
 */
export interface UpdateStaffRequest {
    "id": number;
    "display_name": string;
}

/**
 * User represents a user account (admin or employee)
 */
export interface User {
    "id": number;
    "username": string;

    /**
     * "admin" or "employee"
     */
    "role": string;

    /**
     * human-readable name shown in UI
     */
    "display_name": string;
    "created_at": string;
}

/**
 * UserSession represents the logged-in user's session data sent to the frontend
 */
export interface UserSession {
    "id": number;
    "username": string;
    "role": string;
    "display_name": string;
}
